# Generated by Django 5.1.2 on 2024-10-27 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(default='S/A', max_length=50)),
                ('correo', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')])),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(default='S/A', max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
