# Generated by Django 5.1.2 on 2024-10-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='profesor_a_cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
