# Generated by Django 5.1.2 on 2024-10-29 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_materias_profesor_a_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, null='S/A')),
                ('correo', models.CharField(max_length=30, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')])),
                ('curso', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='materias',
            name='profesor_a_cargo',
            field=models.CharField(max_length=50),
        ),
    ]
