# Generated by Django 5.1.2 on 2024-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_profesor_alter_materias_profesor_a_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='profesor_a_cargo',
            new_name='correo_profe',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='curso',
            field=models.CharField(max_length=50),
        ),
    ]
