# Generated by Django 5.0.6 on 2024-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_profesor_a_cargo_materias_correo_profe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='asistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
