# Generated by Django 5.0.6 on 2024-10-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alumno_asistencia_alter_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(related_name='alumnos', to='API.materias'),
        ),
    ]
