# Generated by Django 5.0.6 on 2024-10-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='materias',
        ),
        migrations.AddField(
            model_name='alumno',
            name='asistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='API.materias'),
        ),
    ]
