# Generated by Django 5.1.2 on 2024-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_alumno_materias_alumno_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='totalClases',
            field=models.IntegerField(default=0),
        ),
    ]
