# Generated by Django 5.0.6 on 2024-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_materias_totalclases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='S/A', max_length=50),
        ),
    ]
