# Generated by Django 5.0.6 on 2024-11-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_profesor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='nombre',
            new_name='materia',
        ),
    ]
