# Generated by Django 5.0.6 on 2024-11-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_rename_materia_materias_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='materia',
            new_name='nombre',
        ),
    ]
