# Generated by Django 5.1.2 on 2024-11-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_rename_materia_asistencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
